### ISSUE TITLE
pip3 install fails for me on Ubuntu

### ISSUE THREAD

**Issue by gogins** [csound-plugins/risset#1]
mkg@xenakis:~$ pip3 install risset
Collecting risset
  Downloading https://files.pythonhosted.org/packages/5c/57/a4ac3bc62b13da1d2f1fe90ea8abfe1649b7aadb96f0b192d3b5c4921a07/risset-0.2.1.tar.gz
Building wheels for collected packages: risset
  Running setup.py bdist_wheel for risset ... done
  Running setup.py clean for risset
Failed to build risset
Installing collected packages: risset
  Running setup.py install for risset ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-umu1ecmh/risset/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xbxztc3l-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /home/mkg/.local/lib/python3.6/site-packages/setuptools/dist.py:485: UserWarning: The version specified ('Traceback (most recent call last):\n  File "./risset.py", line 5, in <module>\n    import dataclasses\nModuleNotFoundError: No module named \'dataclasses\'') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying risset.py -> build/lib
    running install_lib
    copying build/lib/risset.py -> /home/mkg/.local/lib/python3.6/site-packages
    byte-compiling /home/mkg/.local/lib/python3.6/site-packages/risset.py to risset.cpython-36.pyc
    running install_egg_info
    running egg_info
    writing risset.egg-info/PKG-INFO
    writing dependency_links to risset.egg-info/dependency_links.txt
    writing entry points to risset.egg-info/entry_points.txt
    writing top-level names to risset.egg-info/top_level.txt
    reading manifest file 'risset.egg-info/SOURCES.txt'
    writing manifest file 'risset.egg-info/SOURCES.txt'
    Copying risset.egg-info to /home/mkg/.local/lib/python3.6/site-packages/risset-Traceback._most.recent.call.last_..File._._risset.py_.line.5_.in._module_....import.dataclasses_ModuleNotFoundError_.No.module.named._dataclasses_-py3.6.egg-info
    error: [Errno 36] File name too long: '/home/mkg/.local/lib/python3.6/site-packages/risset-Traceback._most.recent.call.last_..File._._risset.py_.line.5_.in._module_....import.dataclasses_ModuleNotFoundError_.No.module.named._dataclasses_-py3.6.egg-info'
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-umu1ecmh/risset/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xbxztc3l-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-umu1ecmh/risset/

**Comment by gogins** [comment]
Oops, it works if use `sudo`.

**Comment by gesellkammer** [comment]
You are probably using an old python/pip. For recent versions of pip, if it can't install in the system directory it falls back to installing in the user directory, which doesn't need sudo. You can achieve the same effect by doing

    pip3 install risset --user
